### ISSUE TITLE
Meta human not moving around 

### ISSUE THREAD

**Issue by Ramkuba** [Off-World-Live-Collaborative/VTuberStudio#6]
### Describe your feature in detail ie where it would be added

The vmc protocol works fine but the meta human is not moving around but just fixed at one place 

### Why would this feature be relevant to other users?

This can complete the full body tracking from the webcam

**Comment by jennnital** [comment]
Hi @Ramkuba this can be solved by linking the pelvic or hip bone with location from VMC. I will be updating this soon!
